# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

# Notes:
# recreate audiobookshelf from scratch as the newer version will fail
#   to work with the old database anyway.
#

# nixos-rebuild switch --flake /etc/nixos#nixos

{
  config,
  pkgs,
  lib,
  modulesPath,
  ...
}:

{
  nix = {
    package = pkgs.nix;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };
  system.stateVersion = "24.05"; # Did you read the comment?

  environment.systemPackages = with pkgs; [
    bashInteractive
    coreutils
    fd
    findutils
    git
    jujutsu
    less
    lsof
    man
    mg
    ncdu
    procps
    shadow
    strace
    util-linux
    vim
    zlib-ng
  ];

  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./lxd.nix
  ];

  #   fileSystems = {
  #     "/" = {
  #       device = "/dev/disk/by-uuid/a41dfb89-85ef-40a0-afb1-97ca6861bd90";
  #       fsType = "ext4";
  #     };
  #     "/backup" = {
  #       device = "/dev/disk/by-uuid/068C27968C277EF5";
  #       fsType = "ntfs";
  #     };
  #     "/stuff" = {
  #       device = "/dev/disk/by-uuid/3884dbcb-1fc1-4d41-94cb-7f488ece86ef";
  #       fsType = "ext4";
  #     };
  #     "/data" = {
  #       device = "/dev/disk/by-uuid/736fc740-dcb2-4251-9b7f-0dd09b6f0bcd";
  #       fsType = "ext4";
  #     };
  #   };

  #   swapDevices = [
  #     {
  #       device = "/swapfile";
  #       size = 4 * 1024; # 4GB
  #     }
  #   ];

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
    firewall.enable = true;
  };
  networking.firewall.allowedTCPPorts = [
    8384 # syncthing web GUI
    22000 # syncthing sync
  ];

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  #   systemd.network = {
  #     enable = true;
  #     networks."enp0s31f6" = {
  #       matchConfig = {
  #         PermanentMACAddress = "1c:1b:0d:1b:44:c4";
  #         Name = "enp0s31f6";
  #       };
  #       networkConfig = {
  #         DHCP = "ipv4";
  #         LinkLocalAddressing = "ipv6";
  #         Address = "192.168.1.43/24";
  #         IPv6AcceptRA = true;
  #       };
  #       dns = [
  #         "8.8.8.8"
  #         "4.4.4.4"
  #       ];
  #       routes = [
  #         {
  #           Destination = "0.0.0.0/0";
  #           Gateway = "192.168.1.1";
  #         }
  #       ];
  #     };
  #   };

  programs.fish.enable = true;

  users.users = {
    james = {
      hashedPasswordFile = "/var/lib/private/james.pw";
      shell = pkgs.fish;
      isNormalUser = true;
      openssh.authorizedKeys.keys = [
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVFCuncf2UzPNMH2qAupg0/8L3pIH6Y86lyfWa6nke/haXITT9xKsjLrau2aAGoyPBpgFah6TIqPIEaHCm8OjYzcpHQLRXbu3mCAK70E23ud8zubBiEZ3GSdvhedrNvxgo9p84UaEIPhDik30HzSiiv2oYrUmnnPFdacMXG8Q99khvSKnC15jylINFDAdzETKidDMV/p0xn5zVydwCxNzChJOb5nXzdTwXZ1YiB1vgRuGeOjZ77SwoTWkqFfDaUT4B7U88pTwOnAvQOIVd9LCQzcMUucAL4QdHK6XXtAciJUrG8I+h4xDt/JmpsQ4WbeYFukQt6pf1cpxSLWPigMhmFAygZZEft+gXkszELpMA6DBqy+VLjJ0/sNZzZvR7UwhG1n9o2OLdwxyw0Shxm0ZeFeFYNeNp6AaficHPEH+wGQuvgHuN35ZEgAw8MGLSoDdDPOxn5Py7gtz5fK4gSN+QtkaNFRIUZULoyBRDxr6SFVqnVvw8CxuCvkKfoygMXQk= james@cow"
      ];
      extraGroups = [ "wheel" ];
    };
  };

  security.sudo.wheelNeedsPassword = false;

  # environment.etc."hass/configuration.yaml".text = ''
  #   default_config:
  #
  #   homeassistant:
  #     name: Falcon
  #     unit_system: imperial
  #     time_zone: "America/Chicago"
  # '';
  systemd.tmpfiles.rules = [
    #   # type path mode user group age argument
    #   "L+ /var/lib/hass/configuration.yaml - - - - /etc/hass/configuration.yaml"
    "z /var/lib/private 0555 root root"
    "z /var/lib/private/james.pw 0600 root root"
    "z /var/lib/private/syncthing-key.pem 0400 syncthing syncthing"
    "z /var/lib/private/syncthing-cert.pem 0440 syncthing syncthing"
  ];

  services.audiobookshelf = {
    enable = true;
    host = "0.0.0.0";
    port = 13378;
    openFirewall = true;
  };

  services.deluge = {
    enable = true;
    web.enable = true;
    web.openFirewall = true;
    web.port = 8112;
    # default password is "deluge"

    # extraPackages = with pkgs; [
    #   deluge
    #   deluge-gtk
    #   deluge-web
    # ];
    # declarative = true;
    # authFile = "/var/lib/private/deluge-auth";
    # openFirewall = true;
    # config = {
    #   "allow_remote" = true;
    #   #   "download_location" = "/var/lib/deluge/Downloads";
    #   "download_location" = "/data/torrents";
    #   "move_completed_path" = "/var/lib/deluge/Completed";
    #   "torrentfiles_location" = "/var/lib/deluge/TorrentFiles";
    #   "max_active_seeding" = 5;
    #   "max_active_downloading" = 3;
    #   "max_upload_speed" = 100000; # in KB/s
    #   "max_download_speed" = 100000; # in KB/s
    # };
  };

  services.home-assistant = {
    enable = true;
    openFirewall = true; # Turning this on requires a declarative config

    config = {
      http.server_port = 8123;
      http.server_host = "0.0.0.0";
    };

    extraComponents = [
      "analytics"
      "isal"
    ];
  };

  services.jellyfin = {
    enable = true;
    openFirewall = true;
  };

  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
    };
  };

  services.syncthing = {
    enable = true;
    openDefaultPorts = true; # This does NOT open the web GUI port, 8384 opened in networking.firewall.allowedTCPPorts
    guiAddress = "0.0.0.0:8384";
    user = "james";
    group = "users";
    configDir = "/home/james/.config/syncthing";
    extraFlags = [ "--no-default-folder" ]; # Don't create default ~/Sync folder
    key = "/var/lib/private/syncthing-key.pem";
    cert = "/var/lib/private/syncthing-cert.pem";
    settings = {
      devices = {
        "pixel8" = {
          id = "KPVQJ5S-WJ4YTRN-5R5JSXU-ARIIPIN-3I7TC3R-M6Q26RG-2XAP3B6-RVXI5QE";
        };
        "cow" = {
          id = "7BSDDTD-QF5PTSR-L24GNLA-3KWU66Y-OAMPDBW-YGGPF2X-LR57MTA-UPMPKAQ";
        };
      };
      folders = {
        "pixel_8_jr4z-photos" = {
          path = "/home/james/sync/pixel8_photos";
          devices = [
            "pixel8"
            "cow"
          ];
        };
        "odl0c-z0c4d" = {
          path = "/home/james/sync/phone";
          devices = [
            "pixel8"
            "cow"
          ];
        };
        "jhuqq-vp3qp" = {
            path = "/home/james/sync/configs";
            devices = ["cow"];
        };
        "nwgye-qxqhz" = {
            path = "/home/james/sync/james_crap";
            devices = ["cow"];
        };
        "jaurg-xzbvu" = {
            path = "/home/james/sync/pics";
            devices = ["cow"];
        };
      };
    };
  };

  services.tailscale.enable = true;
}
